### ISSUE TITLE
Offer for contrubiting

### ISSUE THREAD

**Issue by ghost** [rhardih/serve#1]
Hello @rhardih , I just saw your package from the go trending list. Congrulations, I know how you're feeling!!

I am thinking of this, and don't missunderstand me please but, 

Many packages uses net/http for command line fast-run servers like yours, I think you can do better, using the [Iris](https://github.com/kataras/iris) . 

 I'm not enough good with command line apps in go and these days I don't have much time to deep into this field. If you prefer to use net/http in this package that's ok, it's your decision, but I have to make this 'offer' too: I want to you to be part of the Iris Contrib in [this command line tool](https://github.com/iris-contrib/iris) which is not ready yet, you can delete all files and start from zero with your preffered  way and structure. Think both of them and answer me here or [here](https://gitter.im/kataras/iris) please. Hopes you the bests!!

**Comment by rhardih** [comment]
Hello @kataras,

Iris looks like a cool project, but performance isn't really a concern for this tool. It's just meant to serve a local directory to your own browser and net/http might not be the fastest, but it can still send you a static index.html in something like 8ms, so I'd say that is plenty fast.

I have to admit, that I'm very new to Go and this was just something I mashed together quickly, because I needed http2 and gzip, but also because Go made it easy. It's a hack really, but a useful one. So thank you for the offer, but I'm probably not the right guy to help out on Iris Contrib.

**Comment by ghost** [comment]
You're very kind, thanks you for the nice words.

You have a good point to the http2, gzip is automatically on big files on Iris but http2 not yet supported. 
Go is very nice language I recommend you to stick with it, you will like it more and more :)

If and when you want to join with us, the offer will be open for you, Good luck!!
